/**
 * ManageSpace CRM API
 * ManageSpace CRM API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountResponseCompany } from './accountResponseCompany';
import { AccountResponseContact } from './accountResponseContact';


export interface AccountResponse { 
    /**
     * Account Id
     */
    accountId: string;
    /**
     * Account Name
     */
    accountName: string;
    /**
     * Organization Id
     */
    orgId: string;
    company: AccountResponseCompany;
    contact: AccountResponseContact;
    /**
     * Payment provider ID
     */
    paymentProviderId: string;
    /**
     * Created at
     */
    createdAt: string;
}

