/**
 * ManageSpace CRM API
 * ManageSpace CRM API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyResponseAddress } from './companyResponseAddress';
import { CompanyContactResponse } from './companyContactResponse';
import { CompanyResponseNote } from './companyResponseNote';


export interface AccountResponseCompany { 
    /**
     * Email address
     */
    email: string | null;
    /**
     * Phone number
     */
    phoneNumber: string | null;
    /**
     * Mobile number
     */
    mobileNumber: string;
    /**
     * Fax number
     */
    faxNumber: string | null;
    /**
     * Time of creation
     */
    createdAt: string;
    /**
     * Company Id
     */
    companyId: string;
    /**
     * Company name
     */
    companyName: string;
    /**
     * Notes about the contact
     */
    notes: Array<CompanyResponseNote>;
    /**
     * Company contacts
     */
    companyContacts: Array<CompanyContactResponse>;
    address: CompanyResponseAddress | null;
}

