/**
 * ManageSpace CRM API
 * ManageSpace CRM API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CompanyResponseNote { 
    /**
     * The note about the contact.
     */
    text: string;
    /**
     * The timestamp when the note was created
     */
    createdAt: string;
    /**
     * UUID of the user who created the note
     */
    createdBy: string;
    /**
     * The full name of the person who created the note
     */
    createdByFullName: string;
    /**
     * The timestamp when the note was last updated
     */
    updatedAt: string;
    /**
     * UUID of the user who last updated the note
     */
    updatedBy: string;
    /**
     * Company Note Id
     */
    companyNoteId: string;
}

