/**
 * ManageSpace CRM API
 * ManageSpace CRM API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactResponseAddress } from './contactResponseAddress';


export interface CompanyContactResponse { 
    /**
     * Email address
     */
    email: string | null;
    /**
     * Phone number
     */
    phoneNumber: string | null;
    /**
     * Mobile number
     */
    mobileNumber: string;
    /**
     * Fax number
     */
    faxNumber: string | null;
    /**
     * Time of creation
     */
    createdAt: string;
    /**
     * Contact Id
     */
    contactId: string;
    /**
     * First name
     */
    firstName: string;
    /**
     * Middle name
     */
    middleInitial?: string;
    /**
     * Last name
     */
    lastName: string;
    address: ContactResponseAddress | null;
    /**
     * Account Id
     */
    accountId: string;
    /**
     * Payment provider Id
     */
    paymentProviderId: string;
}

