/**
 * ManageSpace CRM API
 * ManageSpace CRM API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContactResponseCompany { 
    /**
     * Email address
     */
    email: string | null;
    /**
     * Phone number
     */
    phoneNumber: string | null;
    /**
     * Mobile number
     */
    mobileNumber: string;
    /**
     * Fax number
     */
    faxNumber: string | null;
    /**
     * Time of creation
     */
    createdAt: string;
    /**
     * Company Id
     */
    companyId: string;
    /**
     * Company name
     */
    companyName: string;
}

