/**
 * ManageSpace CRM API
 * ManageSpace CRM API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactAddressRequest } from './contactAddressRequest';


export interface CreateContactRequest { 
    /**
     * Email address
     */
    email?: string;
    /**
     * Phone number
     */
    phoneNumber?: string;
    /**
     * Mobile number
     */
    mobileNumber: string;
    /**
     * Fax number
     */
    faxNumber?: string;
    /**
     * Notes
     */
    notes: Array<string>;
    /**
     * First name
     */
    firstName: string;
    /**
     * Middle name
     */
    middleInitial?: string;
    /**
     * Last name
     */
    lastName: string;
    address?: ContactAddressRequest;
}

