/**
 * ManageSpace CRM API
 * ManageSpace CRM API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountResponse } from './accountResponse';


export interface GetAccount200Response { 
    data?: Array<AccountResponse>;
    success?: boolean;
    error?: object;
}

