/**
 * ManageSpace CRM API
 * ManageSpace CRM API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactResponse } from './contactResponse';


export interface GetContactWithAccount200Response { 
    data?: Array<ContactResponse>;
    success?: boolean;
    error?: object;
}

